services:

  app:
    build: ./app
    container_name: flask-app

    ports:
      - "5000:5000"

    environment:
      DB_HOST: postgres
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASSWORD: devpass

  postgres:
    image: postgres:16

    container_name: postgres-db

    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb

    ports:
      - "5433:5432"
